// Built-in exercise library for the Workout tab.
const EXERCISE_DB = [
  { name: "Barbell Bench Press", group: "Chest" },
  { name: "Incline Dumbbell Press", group: "Chest" },
  { name: "Push-Up", group: "Chest" },
  { name: "Cable Fly", group: "Chest" },
  { name: "Barbell Back Squat", group: "Legs" },
  { name: "Romanian Deadlift", group: "Legs" },
  { name: "Leg Press", group: "Legs" },
  { name: "Walking Lunge", group: "Legs" },
  { name: "Leg Extension", group: "Legs" },
  { name: "Leg Curl", group: "Legs" },
  { name: "Calf Raise", group: "Legs" },
  { name: "Deadlift", group: "Back" },
  { name: "Pull-Up", group: "Back" },
  { name: "Barbell Row", group: "Back" },
  { name: "Lat Pulldown", group: "Back" },
  { name: "Seated Cable Row", group: "Back" },
  { name: "Overhead Press", group: "Shoulders" },
  { name: "Lateral Raise", group: "Shoulders" },
  { name: "Face Pull", group: "Shoulders" },
  { name: "Rear Delt Fly", group: "Shoulders" },
  { name: "Barbell Curl", group: "Arms" },
  { name: "Dumbbell Curl", group: "Arms" },
  { name: "Hammer Curl", group: "Arms" },
  { name: "Tricep Pushdown", group: "Arms" },
  { name: "Skull Crusher", group: "Arms" },
  { name: "Dip", group: "Arms" },
  { name: "Plank", group: "Core" },
  { name: "Hanging Leg Raise", group: "Core" },
  { name: "Cable Crunch", group: "Core" },
  { name: "Russian Twist", group: "Core" },
];
